=== gegic/poverenik/xml/xmlSchema/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:zahtev="http://www.ftn.uns.ac.rs/zahtev">
    <xs:element name="zahtev" type="TZahtev"/>
    <xs:simpleType name="TMesto">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="TBroj">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d+\w?)|(bb)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TZahtev" mixed="true">
        <xs:sequence>
            <xs:element name="organ" type="TOrgan"/>
            <xs:element name="naslov" type="xs:string"/>
            <xs:element name="zakon" type="TZakon"/>
            <xs:element name="tip-zahteva" type="TBiranje">
                <xs:key name="kljucZahteva">
                    <xs:selector xpath="izbor"/>
                    <xs:field xpath="@id"/>
                </xs:key>
            </xs:element>
            <xs:element name="tip-informacije" type="xs:string"/>
            <xs:element name="mesto" type="TMesto"/>
            <xs:element name="trazilac-informacije" type="TOsoba"/>
        </xs:sequence>
        <xs:attribute use="required" name="datum" type="xs:date"/>
    </xs:complexType>

    <xs:complexType name="TOrgan">
        <xs:sequence>
            <xs:element name="sediste" type="TAdresa"/>
        </xs:sequence>
        <xs:attribute name="naziv" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="mesto" type="TMesto"/>
        </xs:sequence>
        <xs:attribute use="required" name="ulica" type="xs:string"/>
        <xs:attribute use="required" name="broj" type="TBroj"/>
    </xs:complexType>
    <xs:complexType name="TBiranje">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="izbor" type="TIzbor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TIzbor">
        <xs:choice minOccurs="0">
            <xs:element name="tip-dostave" type="TBiranje">
                <xs:key name="kljucDostave">
                    <xs:selector xpath="izbor"/>
                    <xs:field xpath="@id"/>
                </xs:key>
            </xs:element>
            <xs:element name="drugi-nacin" type="xs:string"/>
        </xs:choice>
        <xs:attribute name="naziv-izbora" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="izabran" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="adresa" type="TAdresa"/>
            <xs:element name="ostali-podaci" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ime" type="xs:string" use="required"/>
        <xs:attribute name="prezime" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="TZakon">
        <xs:sequence>
            <xs:element name="clan" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="stav" minOccurs="0">
                            <xs:complexType>
                                <xs:attribute name="broj" type="xs:positiveInteger" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="broj" type="xs:positiveInteger" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="sluzbeni-glasnik" type="TListObjave"/>
        </xs:sequence>
        <xs:attribute name="naziv" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="TListObjave">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{1,5}/\d\d"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== gegic/poverenik/xml/xmlModel/zahtev.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xmlSchema/zahtev.xsd" datum="2020-12-05">
    <organ naziv="naziv">
        <sediste ulica="ulica" broj="1a">
            <mesto>Tutin</mesto>
        </sediste>
    </organ>

    <naslov> З А Х Т Е В </naslov>
    за приступ информацији од јавног значаја

    <zakon naziv="Закон о слободном приступу информацијама од јавног значаја">
        <clan broj="15">
            <stav broj="1"/>
        </clan>
        <sluzbeni-glasnik>
            <broj>120/04</broj>
            <broj>54/07</broj>
            <broj>104/09</broj>
            <broj>36/10</broj>
        </sluzbeni-glasnik>
    </zakon>
    На основу Закона...
    од горе наведеног органа захтевам:*
    <tip-zahteva>
        <izbor id="Z1" naziv-izbora="обавештење да ли поседује тражену информацију"/>
        <izbor id="Z2" naziv-izbora="увид у документ који садржи тражену информацију"/>
        <izbor id="Z3" naziv-izbora="копију документа који садржи тражену информацију"/>
        <izbor id="Z4" naziv-izbora="достављање копије документа који садржи тражену информацију">
            <tip-dostave>
                <izbor id="D1" naziv-izbora="поштом"/>
                <izbor id="D2" naziv-izbora="електронском поштом"/>
                <izbor id="D3" naziv-izbora="факсом"/>
                <izbor id="D4" naziv-izbora="на други начин">
                    <drugi-nacin></drugi-nacin>
                </izbor>
            </tip-dostave>
        </izbor>
    </tip-zahteva>

    

    Овај захтев се односи на следеће информације:
    <tip-informacije> </tip-informacije>

    
    <mesto></mesto>
    
    <trazilac-informacije ime="ip" prezime="p">
        <adresa ulica="u" broj="bb">
            <mesto>Tutin</mesto>
        </adresa>
        <ostali-podaci> </ostali-podaci>
    </trazilac-informacije>
</zahtev>
