=== gegic/poverenik/xml/xmlSchema/zalbanaodluku.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:zno="http://www.ftn.uns.ac.rs/zabla-na-odluku">
    <xs:element name="zalba" type="TZalba"/>
    <xs:complexType mixed="true" name="TZalba">
        <xs:sequence>
            <xs:element name="svrha" type="xs:string"/>
            <xs:element name="primalac" type="TOrgan"/>
            <xs:element name="zalilac" type="TLice"/>
            <xs:element name="protiv" type="TOdluka"/>
            <xs:element name="datum" type="xs:date"/>
            <xs:element default="у целости" name="deo-pobijanja" type="xs:string"/>
            <xs:element name="zakon" type="TZakon"/>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="podnosilac" type="TOsoba"/>
        </xs:sequence>
        <xs:attribute name="datum" type="xs:date" use="required"/>
    </xs:complexType>
    <xs:complexType name="TOdluka">
        <xs:sequence>
            <xs:element name="donosilac" type="TOrgan"/>
        </xs:sequence>
        <xs:attribute name="broj" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\d{1,5}/\d\d"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="datum" type="xs:date" use="required"/>
    </xs:complexType>
    <xs:complexType name="TOrgan">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:attribute name="naziv" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element name="adresa" type="TAdresa"/>
            <xs:element minOccurs="0" name="ostali-podaci" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOsoba">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:attribute name="ime" type="xs:string" use="required"/>
                <xs:attribute name="prezime" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="mesto" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ulica" type="xs:string" use="required"/>
        <xs:attribute name="broj" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="(\d+\w?)|(bb)"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TZakon">
        <xs:sequence>
            <xs:element minOccurs="0" name="clan">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="stav">
                            <xs:complexType>
                                <xs:attribute name="broj" type="xs:positiveInteger" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="broj" type="xs:positiveInteger" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="sluzbeni-glasnik" type="TListObjave"/>
        </xs:sequence>
        <xs:attribute name="naziv" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="TListObjave">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{1,5}/\d\d"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== gegic/poverenik/poverenik/src/main/resources/data/zalbanaodluku.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba  
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xmlSchema/zalbanaodluku.xsd" 
    xmlns:zo="http://team14.xml.com/rdf/zalbenaodluku"
    xmlns:pred="http://team14.xml.com/rdf/zalbenaodluku/predicate/"
    vocab="http://team14.xml.com/rdf/zalbenaodluku/predicate/"
    about="http://team14.xml.com/rdf/zalbenaodluku/806a5cbe-f52a-4f0e-9028-3f874cf0a8f8"
    id="806a5cbe-f52a-4f0e-9028-3f874cf0a8f8"
    >
    <datum>2021-01-09</datum>
    <primalac>
        <adresa>
            <mesto property="pred:mesto-poverenika" datatype="xs:string">Beograd</mesto>
            <ulica property="pred:ulica-poverenika" datatype="xs:string">Nemanjina 12</ulica>
        </adresa>
        <naziv property="pred:naziv-poverenika" datatype="xs:string">Drzavni poverenik</naziv>
    </primalac>
    
    <zalilac id="ad440aa9-b8ca-4e2c-8602-1c323bbf04a9">
        <adresa>
            <mesto property="pred:mesto-podnosioca" datatype="xs:string">Tutin</mesto>
            <ulica property="pred:ulica-podnosioca" datatype="xs:string">Svetozara Markovica bb</ulica>
        </adresa>
        <ostali-podaci></ostali-podaci>
        <ime-prezime property="ime-prezime-podnosioca" datatype="xs:string">Haris Gegic</ime-prezime>
    </zalilac>
    <protiv id="081c6f67-2cc8-40ca-b057-b5a4c2896d3f">
        <broj>2/2021</broj>
        <datum>2021-01-06</datum>
        <donosilac>
            <adresa>
                <mesto property="pred:mesto-ustanove" datatype="xs:string">Novi Sad</mesto>
                <ulica property="pred:ulica-ustanove" datatype="xs:string">Cara Lazara 12</ulica>
            </adresa>
            <naziv property="pred:naziv-ustanove" datatype="xs:string">Neka ustanova</naziv>
        </donosilac>
    </protiv>
  
    <zahtev id="5fb41eaa-0cd6-48ae-97d6-b2f51799afe3">
        <datum property="pred:datum-zahteva" datatype="xs:date">2020-10-03</datum>
        <opis-zahteva property="pred:opis-zahteva" datatype="xs:string">O izvrsenom inspekcijskom nadzoru</opis-zahteva>
    </zahtev>
    <deo-pobijanja></deo-pobijanja> 
    <zakon>
        <naziv>Zakon o slobodnom pristupu informacijama od javnog znacaja</naziv>
        <clan broj="22">
            <stav broj="1"/>
        </clan>
    </zakon>
    <mesto>Tutin</mesto>
    <podnosilac id="ad440aa9-b8ca-4e2c-8602-1c323bbf04a9">
        <adresa>
            <mesto property="pred:mesto-podnosioca" datatype="xs:string">Tutin</mesto>
            <ulica property="pred:ulica-podnosioca" datatype="xs:string">Svetozara Markovica bb</ulica>
        </adresa>
        <ime-prezime property="pred:ime-prezime-podnosioca" datatype="xs:string">Haris Gegic</ime-prezime>
    </podnosilac>
    
</zalba>

=== gegic/poverenik/xml/xmlModel/zalbanaodluk.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xmlSchema/zalbanaodluku.xsd" datum="2020-12-05">
    <svrha>
        ЖАЛБА  ПРОТИВ  ОДЛУКЕ ОРГАНА  ВЛАСТИ КОЈОМ ЈЕ 
        ОДБИЈЕН ИЛИ ОДБАЧЕН ЗАХТЕВ ЗА ПРИСТУП ИНФОРМАЦИЈИ
    </svrha>
    <primalac naziv="Поверенику за информације од јавног значаја и заштиту података о личности">
        <adresa ulica="Булевар краља Александрa" broj="15">
            <mesto>Београд</mesto>
        </adresa>
    </primalac>
    
    Ж А Л Б А 
    
    <zalilac ime="i" prezime="p" xsi:type="Osoba">
        <adresa ulica="ulica" broj="1b">
            <mesto> </mesto>
        </adresa>
    </zalilac>
    против решења-закључка 
    
    <protiv broj="13/20" datum="2020-11-04">
        <donosilac naziv="naziv">
            <adresa ulica="ulica" broj="12">
                <mesto></mesto>
            </adresa>
        </donosilac>
    </protiv>
  
    Наведеном одлуком органа власти (решењем, закључком, обавештењем у писаној форми са елементима одлуке) , супротно закону, одбијен-одбачен је мој захтев који сам поднео/ла-упутио/ла дана <datum>2020-11-01</datum>
    године и тако ми ускраћено-онемогућено остваривање уставног и законског права на слободан приступ информацијама од јавног значаја. Oдлуку побијам
    <deo-pobijanja/> 
    јер није заснована на Закону о слободном приступу информацијама од јавног значаја.
    На основу изнетих разлога, предлажем да Повереник уважи моју жалбу,  поништи одлука првостепеног органа и омогући ми приступ траженој/им  информацији/ма.
    Жалбу подносим благовремено, у законском року утврђеном у члану 22. ст. 1. Закона о слободном приступу информацијама од јавног значаја.
    <zakon naziv="Закон о слободном приступу информацијама од јавног значаја">
        <clan broj="22">
            <stav broj="1"/>
        </clan>
    </zakon>
    
    <mesto> </mesto>
    
    <podnosilac ime="i" prezime="p">
        <adresa ulica="ulica" broj="23c">
            <mesto> </mesto>
        </adresa>
        <ostali-podaci> </ostali-podaci>
    </podnosilac>
</zalba>
