=== gegic/poverenik/xml/xmlSchema/zalbacutanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:zalba-cutanje="http://www.ftn.uns.ac.rs/zalba-cutanje">
    <xs:include schemaLocation="poverenik.xsd"/>
    <xs:element name="zalba-cutanje" type="Zalba"/>
    <xs:complexType mixed="true" name="Zalba">
        <xs:sequence>
            <xs:element name="svrha" type="xs:string"/>
            <xs:element name="primalac" type="Organ"/>
            <xs:element name="zakon" type="Akt"/>
            <xs:element name="protiv" type="Organ"/>
            <xs:element name="razlog" type="BiranjeRazloga">
                <xs:key name="kljucRazloga">
                    <xs:selector xpath="izbor"/>
                    <xs:field xpath="@id"/>
                </xs:key>
            </xs:element>
            <xs:element name="datum-zahteva" type="xs:date"/>
            <xs:element name="podaci-o-zahtevu" type="xs:string"/>
            <xs:element name="napomena" type="xs:string"/>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="podnosilac" type="Osoba"/>
        </xs:sequence>
        <xs:attribute name="datum" type="xs:date"/>
    </xs:complexType>
    <xs:complexType name="IzborRazloga">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="naziv" type="xs:string" use="required"/>
                <xs:attribute name="id" type="xs:ID" use="required"/>
                <xs:attribute name="izabran" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="BiranjeRazloga">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="izbor" type="IzborRazloga"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== gegic/poverenik/xml/xmlModel/zalbacutanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba-cutanje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xmlSchema/zalbacutanje.xsd" datum="2020-12-05">
    
    <svrha> ЖАЛБА КАДА ОРГАН ВЛАСТИ НИЈЕ ПОСТУПИО/ није поступио у целости/ ПО ЗАХТЕВУ ТРАЖИОЦА У
        ЗАКОНСКОМ РОКУ (ЋУТАЊЕ УПРАВЕ) </svrha>

    <primalac naziv="Повереникy за информације од јавног значаја и заштиту података о личности">
        <adresa ulica="Булевар краља Александрa" broj="15">
            <mesto> Београд </mesto>
        </adresa>
    </primalac>
    
    <zakon naziv="Закон о слободном приступу информацијама од јавног значаја">
        <clan broj="22"/>
    </zakon>
    У складу са чланом 22. Закона о слободном приступу информацијама од јавног значаја подносим: 
    Ж А Л Б У
    против
    <protiv> </protiv>
    <razlog>
        <izbor naziv-izbora="није поступио" id="R1"/> 
        <izbor naziv-izbora="није поступио у целости" id="R2"/>  
        <izbor naziv-izbora="у законском року" id="R3"/>  
    </razlog> 
    по мом захтеву за слободан приступ информацијама од јавног значаја који сам поднео
    том органу дана <datum-zahteva>2020-12-01</datum-zahteva> године, а којим сам тражио/ла да ми се у складу са
    Законом о слободном приступу информацијама од јавног значаја омогући увид- копија документа
    који садржи информације о /у вези са: 
    <podaci-o-zahtevu> </podaci-o-zahtevu>
    
    На основу изнетог, предлажем да Повереник уважи моју жалбу и омогући ми приступ траженој/им  информацији/ма.
    Као доказ , уз жалбу достављам копију захтева са доказом о предаји органу власти.
    <napomena>Код жалбе  због непоступању по захтеву у целости, треба приложити и добијени одговор органа власти.</napomena>


    <mesto> </mesto>
    
    <podnosilac ime="i" prezime="p">
        <adresa ulica="u" broj="bb">
            <mesto>Mesto</mesto>
           
        </adresa>
        <ostali-podaci></ostali-podaci>
    </podnosilac>
</zalba-cutanje>
